/**
 * Created by Mesogene on 7/15/16.
 */
module.exports =function(grunt){
    grunt.initConfig({
        watch:{
            jade:{
                files:['views/**'],//-传递目录
                options:{
                    livereload:true
                }
            },
            js:{
                files:['public/js/**','models/**/*/.js','schemas/**/*.js'],
                options:{
                    livereload:true
                }
            },
            uglify:{
                files:['public/**/*.js'],
                tasks:['jshint'],
                options:{
                    livereload:true
                }
            },
            styles:{
            files:['public/**/*.less'],
            task:['less'],
            options:{
            nospawm:true
        }
        }
        },
        jshint:{
            options:{
                jshinttrc:'.jshintrc',
                ignores:['public/libs/**/*.js']
            },
            all:['public/js/*.js','test/**/*.js','app/**/*.js']
        },

        less:{
            development:{
                options:{
                    compress:true,
                    yuicompress:true,
                    optimization:2
                },
                files:{
                    'public/build/index.css':'public/less/index.less'
                }
            }
        },
        nodemon:{
            dev:{
                options:{
                    file:'app.js',//可以去官网搜索，查看意思
                    args:[],
                    ignoredFiles:['README.md','node-modules/**','.DS_Store'],
                    watchedExtensions:['js'],
                    watchedFolders:['./'],
                    debug:true,
                    delayTime:1,
                    env:{
                        PORT:3002
                    },
                    cwd:__dirname
                }
            }
        },

        mochaTest:{
            options:{
                reporter:'spec'
            },
            src:['test/**/*.js']
        },

        concurrent:{
            tasks:['nodemon','watch','less','uglify','jshint'],
            options:{
                logConcurrentOutput:true
            }
        }
    })
    grunt.loadNpmTasks('grunt-contrib-watch');//有改动时刷新,重新执行
    grunt.loadNpmTasks('grunt-nodemon');//时时监听APP.js,自动重启
    grunt.loadNpmTasks('grunt-concurrent');//针对慢任务，组塞
    grunt.loadNpmTasks('grunt-mocha-test')
    grunt.loadNpmTasks('grunt-contrib-less')
    grunt.loadNpmTasks('grunt-contrib-uglify')
    grunt.loadNpmTasks('grunt-contrib-jshint')

    grunt.option('force',true);
    grunt.registerTask('default',['concurrent'])
}